---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # chef_omnibus_install_options: -P chefdk
  # chef_omnibus_root: /opt/chefdk

# Default verifier is InSpec.
verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[jenkins_ubuntu::default]
      - recipe[my_pipeline_ubuntu::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
